openapi: 3.0.0
info:
  title: helloworld
  version: '1.0'
  description: Sample OpenAPI Spec.
servers:
  - url: 'http://localhost:3000'
paths:
  /api:
    get:
      summary: Your GET endpoint
      tags:
        - Sample
      responses:
        '200':
          description: 'return "Hello, World!"'
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json;charset=UTF-8
          content:
            application/json:
              schema:
                title: ResponseMessage
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
                x-examples:
                  example-1:
                    message: 'Hello, World?'
                description: Sample API Response type
              examples:
                example-ok:
                  value:
                    message: 'Hello, World!'
      operationId: get-api
      description: sample api
      parameters: []
components:
  schemas: {}
  securitySchemes: {}
security: []
tags:
  - name: Sample
    description: Sample API
