openapi: 3.0.0
info:
  title: helloworld
  version: '1.0'
  description: Sample OpenAPI Spec.
servers:
  - url: 'https://raw.githubusercontent.com/penpen39/openapi-sample/master'
paths:
  /api:
    get:
      summary: Your GET endpoint
      tags:
        - Sample
      responses:
        '200':
          description: 'return "Hello, World!"'
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json;charset=UTF-8
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/penpen39/openapi-sample/master/ResponseMessage.v1.yaml'
              examples:
                example-ok:
                  value:
                    message: 'Hello, World!'
      operationId: get-api
      description: sample api
      parameters: []
components:
  schemas: {}
  securitySchemes: {}
tags:
  - name: Sample
    description: Sample API
security: []
